# Generated by Django 5.0.3 on 2024-04-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("timestamp",)},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="date_added",
            new_name="timestamp",
        ),
    ]
