# Generated by Django 5.0.3 on 2024-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyerchatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawExplainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_input", models.TextField()),
                ("_output", models.TextField()),
            ],
            options={
                "db_table": "t_law_explainer",
            },
        ),
    ]
