# Generated by Django 5.0.3 on 2024-05-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="card_last_four",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
