# Generated by Django 5.0.4 on 2024-05-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_app", "0002_invoice_card_last_four_invoice_payment_reference"),
        ("case_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="case_app.case",
            ),
        ),
    ]
